{% set name = "halotools" %}
{% set version = "0.7" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a56e0bf32ac02a3bceacdc6669a6e1b7455f6365392ae35d2674558e2e2ab863
  patches:
    # patch from Matt Craig
    - setup.py.diff

build:
  number: 1
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]    
  host:
    - python
    - setuptools
    - numpy
    - cython
  run:
    - python
    - astropy >=1
    - {{ pin_compatible('numpy') }}
    - scipy
    - beautifulsoup4
    - requests

test:
  requires:
    - pytest-astropy
  imports:
    - halotools
    - halotools.empirical_models
    - halotools.empirical_models.abunmatch
    - halotools.empirical_models.assembias_models
    - halotools.empirical_models.component_model_templates
    - halotools.empirical_models.composite_models
    - halotools.empirical_models.composite_models.hod_models
    - halotools.empirical_models.composite_models.sfr_models
    - halotools.empirical_models.composite_models.smhm_models
    - halotools.empirical_models.factories
    - halotools.empirical_models.occupation_models
    - halotools.empirical_models.occupation_models.engines
    - halotools.empirical_models.phase_space_models
    - halotools.empirical_models.phase_space_models.analytic_models
    - halotools.empirical_models.phase_space_models.analytic_models.centrals
    - halotools.empirical_models.phase_space_models.analytic_models.satellites
    - halotools.empirical_models.phase_space_models.analytic_models.satellites.nfw
    - halotools.empirical_models.phase_space_models.analytic_models.satellites.nfw.conc_mass
    - halotools.empirical_models.phase_space_models.analytic_models.satellites.nfw.kernels
    - halotools.empirical_models.phase_space_models.subhalo_based_models
    - halotools.empirical_models.sfr_models
    - halotools.empirical_models.smhm_models
    - halotools.extern
    - halotools.mock_observables
    - halotools.mock_observables.counts_in_cells
    - halotools.mock_observables.counts_in_cells.engines
    - halotools.mock_observables.group_identification
    - halotools.mock_observables.group_identification.test_groups
    - halotools.mock_observables.isolation_functions
    - halotools.mock_observables.isolation_functions.engines
    - halotools.mock_observables.large_scale_density
    - halotools.mock_observables.pair_counters
    - halotools.mock_observables.pair_counters.cpairs
    - halotools.mock_observables.pair_counters.marked_cpairs
    - halotools.mock_observables.pair_counters.test_pair_counters
    - halotools.mock_observables.pairwise_velocities
    - halotools.mock_observables.pairwise_velocities.engines
    - halotools.mock_observables.radial_profiles
    - halotools.mock_observables.radial_profiles.engines
    - halotools.mock_observables.surface_density
    - halotools.mock_observables.surface_density.engines
    - halotools.mock_observables.two_point_clustering
    - halotools.mock_observables.void_statistics
    - halotools.sim_manager
    - halotools.utils

about:
  home: http://halotools.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: Package for studying large scale structure, cosmology, and galaxy evolution using N-body simulations and halo models.
  description: |
    Halotools is a specialized python package for building and testing models
    of the galaxy-halo connection, and analyzing catalogs of dark matter
    halos. The core functionality of the package includes: Fast generation of
    synthetic galaxy populations using HODs, abundance matching, and related
    methods; Efficient algorithms for calculating galaxy clustering, lensing,
    z-space distortions, and other astronomical statistics; A modular, object-
    oriented framework for designing your own galaxy evolution model; End-to-
    end support for reducing halo catalogs and caching them as fast-loading
    hdf5 files
  doc_url: http://halotools.readthedocs.io
  dev_url: https://github.com/astropy/halotools

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - aphearin
